# Generated by Django 4.2.5 on 2023-10-13 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_gamescore_user_name_gamescore_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamescore',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
