# Generated by Django 4.2.5 on 2023-10-13 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_gamescore_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamescore',
            name='slug',
            field=models.SlugField(default='foo', editable=False, unique=True),
            preserve_default=False,
        ),
    ]
